#! /bin/sh
#Autostart
$HOME/.config/bspwm/autostart.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"

#BSPWM configuration
bspc config border_radius       8
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


#Monitor configuration
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10

## workspace 1 (terminals)
bspc rule -a Alacritty desktop=1 state=tiled focus=on follow=on
bspc rule -a URxvt desktop='^1' state=floating focus=off

## workspace 2 (web browsers)
bspc rule -a "Google-chrome" state=tiled manage=on layer=normal desktop=2
bspc rule -a "firefox" state=pseudo-tiled manage=on layer=normal focus=on follow=on desktop=2
bspc rule -a "privateinternetaccess" state=floating manage=on layer=normal desktop=2
bspc rule -a Bitwarden desktop='^2' state=floating follow=on

## workspace 3 (file-manager)
bspc rule -a "Thunar" state=pseudo-tiled manage=on layer=normal desktop=3
bspc rule -a "FileZilla" state=floating manage=on layer=normal desktop=3

## workspace 4 (multimedia)
bspc rule -a plexmediaplayer desktop='^4' state=fullscreen
bspc rule -a vlc desktop='^4' state=fullscreen
bspc rule -a Plexamp state=floating follow=on manage=on layer=normal desktop=4
bspc rule -a Sonata state=floating manage=on layer=normal follow=on desktop=4
bspc rule -a ncmpcpp2 state=tiled desktop='^4' follow=on

# workspace 5 (text-editors)
bspc rule Subl state=fullscreen manage=on layer=normal follow=on desktop=5
bspc rule -a libreoffice desktop='^5' state=fullscreen follow=on
bspc rule -a kate desktop='^5' state=fullscreen follow=on
bspc rule -a fontmatrix='^5' state=fullscreen
bspc rule -a libreoffice-base desktop='^5' state=fullscreen follow=on
bspc rule -a libreoffice-calc desktop='^5' state=fullscreen follow=on
bspc rule -a libreoffice-draw desktop='^5' state=fullscreen follow=on
bspc rule -a libreoffice-impress desktop='^5' state=fullscreen follow=on
bspc rule -a libreoffice-math desktop='^5' state=fullscreen follow=on
bspc rule -a libreoffice-writer desktop='^5' state=fullscreen follow=on
bspc rule -a libreoffice-startcenter desktop='^5' follow=on focus=on
bspc rule -a meld desktop='^5' state=fullscreen follow=on

# workspace 6 (system-settings)
bspc rule -a xscreensaver-settings desktop='^6' state=fullscreen follow=on
bspc rule -a lxappearance desktop='^6' state=fullscreen follow=on
bspc rule -a pavucontrol desktop='^6' state=floating follow=on
bspc rule -a arandr desktop='^6' state=floating follow=on
bspc rule -a blueberry desktop='^6' state=floating follow=on

# workspace 7 (graphic-editors)
bspc rule -a gimp desktop='^7' state=fullscreen follow=on

# workspace 8 (Email)
bspc rule -a thunderbird desktop=^8 state=fullscreen focus=on follow=on

# workspace 9 (chat)
bspc rule -a discord desktop=^9 state=tiled
